name:                plananalysis
version:             0.1.0.0
github:              "Hazelfire/plananalysis"
license:             BSD3
author:              "Sam Nolan"
maintainer:          "samnolan555@gmail.com"
copyright:           "2020 Sam Nolan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hazelfire/plananalysis#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- text

ghc-options:
  - -Wall
library:
  source-dirs: src

executables:
  plan:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plananalysis

tests:
  plananalysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plananalysis
